trigger:
    - production

stages:
    - stage: Build
      displayName: Compile Native Binaries
      jobs:
        - job: Build
          displayName: Build
          pool:
            vmImage: "ubuntu-latest"
          steps:
            - task: Bash@3
              displayName: Version bump and commit
              inputs:
                targetType: 'inline'
                script: |
                  sudo apt update
                  sudo apt install jq -y
                  version=$(jq -r ".version" package.json)
                  version=$(echo $version | perl -pe 's/\.[\d]+$/$(Build.BuildId)/')
                  jq '.version="$version"' package.json > package.tmp.json && mv package.tmp.json package.json
            - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3 
              displayName: Yarn Install
            - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
              displayName: 'Pkg Compile'
              inputs:
                arguments: compile
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'echo ''//registry.npmjs.org/:_authToken=$(NPM_TOKEN)'' > .npmrc'
            - task: Npm@1
              inputs:
                command: 'publish'
                publishRegistry: 'registry.npmjs.org'
            - task: CopyFiles@2
              displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
              inputs:
                SourceFolder: bin
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishPipelineArtifact@1
              displayName: Publish
              inputs:
                targetPath: '$(Build.ArtifactStagingDirectory)'
                artifact: binaries



