version: 1.0.0
name: dappstarter_cli
description: A sample command-line application.
homepage: https://www.trycrypto.com
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  args: ^1.5.2
  http: ^0.12.0+4
  archive: ^2.0.13
  path: ^1.6.4
  console: ^3.1.0
  dotenv: ^2.0.0
